services:
    sonata.admin.sis_tags.tag:
        class: SmartSystems\TagsBundle\Admin\TagAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "General", label: "Tags" }
        arguments:
            - ~
            - SmartSystems\TagsBundle\Entity\Tag
            - ~
        calls:
            - [ setTranslationDomain, [SmartSystemsTagsBundle]]
