services:
    smart_information_systems_tags.form.type.tags:
        class: SmartInformationSystems\TagsBundle\Form\Type\TagsType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }
    smart_information_systems_tags.form.type.tag_relations:
        class: SmartInformationSystems\TagsBundle\Form\Type\TagRelationsType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }
    smart_information_systems_file.doctrine.subscriber:
        class: SmartInformationSystems\TagsBundle\EventListener\DoctrineSubscriber
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [ setTagRelationService, ['@smart_information_systems_file.tag_relation']]
    smart_information_systems_file.tag_relation:
        class: SmartInformationSystems\TagsBundle\Service\TagRelationService
        lazy: true
        arguments:
            - "@doctrine.orm.entity_manager"
